version: '3.1'
services:
  API:
    image: trchdev/forest:riskyforest_ver2
    ports:
      - "8860:8860"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SERVER_SERVLET_CONTEXT_PATH=/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL/riskyforest
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=AssAssAss122
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=AssAssAss122
      - POSTGRES_USER=postgres
      - POSTGRES_DB=riskyforest
    volumes:
      - PostgreSQL:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  PostgreSQL: